In [1]:
import numpy as np

In [5]:
arr_zeros = np.zeros((3,4))
arr_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
arr_ones = np.ones((3,4))
arr_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
arr_full = np.full((5,5),7)
arr_full

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [11]:
arr = np.arange(0,51,10)
arr

array([ 0, 10, 20, 30, 40, 50])

In [20]:
arr_ran = np.random.rand(2,3)
arr_ran

array([[0.89431435, 0.68054889, 0.22705168],
       [0.70551894, 0.17145708, 0.50611514]])

In [45]:
# 1 ~ 10 수로 100개 뽑기
np.random.seed() # 시드에 숫자를  입력하면 그숫자의 해당하는 랜덤 숫자가 나온다.
np.random.randint(1, 11, 100)

array([ 9,  6,  2,  3,  3,  8,  7,  2, 10,  3,  9,  1,  5,  2,  1,  2,  7,
        9,  4,  4,  8, 10,  6,  5,  7,  8, 10,  4,  5,  4,  4, 10,  3, 10,
        1,  4,  9,  8,  9, 10,  5,  6, 10,  9,  6,  2,  5,  6,  1,  2,  4,
       10,  1, 10,  8,  4,  6,  2,  9,  9,  2,  4,  7,  2,  6,  1,  2,  9,
        1,  3,  3,  6,  3,  1,  1,  3,  1,  7,  6,  9,  4,  2,  3,  3,  5,
        8,  2,  9,  7,  1,  3,  5,  5,  1,  9, 10,  2,  3,  1,  2])

In [78]:
a=np.random.randint(2, 10, size=(2, 2))
print(a) 

[[7 7]
 [3 3]]


In [ ]:
arr3 = np.array